name: rfc_6902
version: 0.0.0-nullsafety.0
description: JSON Patch (RFC 6902).
homepage: "https://github.com/f3ath/rfc-6902-dart"

environment:
  sdk: '>=2.12.0-29 <3.0.0'

dependencies:
  rfc_6901: ^0.0.0-nullsafety

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
  test_coverage: ^0.5.0

