name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image:  dart:stable
    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: git config --global --add safe.directory '*' && git submodule update --init --recursive
      - name: Install dependencies
        run: dart pub get
      - name: Formatter
        run: dartfmt --dry-run --set-exit-if-changed example lib test
      - name: Analyzer
        run: dart analyze --fatal-infos --fatal-warnings
      - name: Tests
        run: dart run test_coverage --no-badge --print-test-output --min-covera
